/**
 * Etiquetas del modelo en espanol. BORRADOR para la demo, pendiente de revision
 * clinica: viene de docs/etiquetas_es_borrador.csv en ecg-pipeline.
 */

export const LABELS_ES: Readonly<Record<string, string>> = {
  'ABNORMAL ECG': 'ECG anormal',
  'NORMAL SINUS RHYTHM': 'ritmo sinusal normal',
  'NORMAL ECG': 'ECG normal',
  'SINUS RHYTHM': 'ritmo sinusal',
  'SINUS BRADYCARDIA': 'bradicardia sinusal',
  'ATRIAL FIBRILLATION': 'fibrilación auricular',
  'SINUS TACHYCARDIA': 'taquicardia sinusal',
  'otherwise normal ecg': 'por lo demás, ECG normal',
  'LEFT AXIS DEVIATION': 'desviación del eje a la izquierda',
  'PREMATURE VENTRICULAR COMPLEXES': 'extrasístoles ventriculares',
  'BORDERLINE ECG': 'ECG límite',
  'RIGHT BUNDLE BRANCH BLOCK': 'bloqueo de rama derecha',
  'SEPTAL INFARCT': 'infarto septal',
  'LEFT ATRIAL ENLARGEMENT': 'crecimiento auricular izquierdo',
  'NONSPECIFIC T WAVE ABNORMALITY': 'anomalía inespecífica de la onda T',
  'LOW VOLTAGE QRS': 'bajo voltaje del QRS',
  'PREMATURE ATRIAL COMPLEXES': 'extrasístoles auriculares',
  'ANTERIOR INFARCT': 'infarto anterior',
  'INCOMPLETE RIGHT BUNDLE BRANCH BLOCK': 'bloqueo incompleto de rama derecha',
  'PREMATURE SUPRAVENTRICULAR COMPLEXES': 'extrasístoles supraventriculares',
  'LEFT BUNDLE BRANCH BLOCK': 'bloqueo de rama izquierda',
  'NONSPECIFIC T WAVE ABNORMALITY NOW EVIDENT IN':
    'anomalía inespecífica de la onda T, ahora evidente en',
  'NONSPECIFIC T WAVE ABNORMALITY NO LONGER EVIDENT IN':
    'anomalía inespecífica de la onda T, ya no evidente en',
  'T WAVE INVERSION NOW EVIDENT IN': 'inversión de la onda T, ahora evidente en',
  'LATERAL INFARCT': 'infarto lateral',
  'NONSPECIFIC ST ABNORMALITY': 'anomalía inespecífica del segmento ST',
  'LEFT VENTRICULAR HYPERTROPHY': 'hipertrofia ventricular izquierda',
  'T WAVE INVERSION NO LONGER EVIDENT IN': 'inversión de la onda T, ya no evidente en',
  'WITH RAPID VENTRICULAR RESPONSE': 'con respuesta ventricular rápida',
  'QT HAS SHORTENED': 'el QT se ha acortado',
  'QT HAS LENGTHENED': 'el QT se ha prolongado',
  'FUSION COMPLEXES': 'complejos de fusión',
  'ATRIAL FLUTTER': 'aleteo auricular',
  'MARKED SINUS BRADYCARDIA': 'bradicardia sinusal marcada',
  'WITH SINUS ARRHYTHMIA': 'con arritmia sinusal',
  'NONSPECIFIC ST AND T WAVE ABNORMALITY': 'anomalía inespecífica del ST y de la onda T',
  'LEFT ANTERIOR FASCICULAR BLOCK': 'bloqueo fascicular anterior izquierdo',
  'RIGHT AXIS DEVIATION': 'desviación del eje a la derecha',
  'ECTOPIC ATRIAL RHYTHM': 'ritmo auricular ectópico',
  'UNDETERMINED RHYTHM': 'ritmo indeterminado',
  'ANTEROSEPTAL INFARCT': 'infarto anteroseptal',
  'RIGHTWARD AXIS': 'eje desviado hacia la derecha',
  'ST NOW DEPRESSED IN': 'el segmento ST está ahora descendido en',
  'WITH SHORT PR': 'con PR corto',
  'WITH MARKED SINUS ARRHYTHMIA': 'con arritmia sinusal marcada',
  'ST NO LONGER DEPRESSED IN': 'el segmento ST ya no está descendido en',
  'INVERTED T WAVES HAVE REPLACED NONSPECIFIC T WAVE ABNORMALITY IN':
    'las ondas T invertidas han reemplazado a la anomalía inespecífica de la onda T en',
  'NON-SPECIFIC CHANGE IN ST SEGMENT IN': 'cambio inespecífico del segmento ST en',
  'NONSPECIFIC T WAVE ABNORMALITY HAS REPLACED INVERTED T WAVES IN':
    'la anomalía inespecífica de la onda T ha reemplazado a las ondas T invertidas en',
  'JUNCTIONAL RHYTHM': 'ritmo de la unión',
  'ELECTRONIC ATRIAL PACEMAKER': 'marcapasos electrónico auricular',
  'ABERRANT CONDUCTION': 'conducción aberrante',
  'ELECTRONIC VENTRICULAR PACEMAKER': 'marcapasos electrónico ventricular',
  'T WAVE INVERSION LESS EVIDENT IN': 'inversión de la onda T, menos evidente en',
  'ANTEROLATERAL INFARCT': 'infarto anterolateral',
  'WITH REPOLARIZATION ABNORMALITY': 'con anomalía de la repolarización',
  "RSR' OR QR PATTERN IN V1 SUGGESTS RIGHT VENTRICULAR CONDUCTION DELAY":
    "patrón RSR' o QR en V1, sugestivo de retraso de la conducción ventricular derecha",
  'T WAVE INVERSION MORE EVIDENT IN': 'inversión de la onda T, más evidente en',
  'WIDE QRS RHYTHM': 'ritmo con QRS ancho',
  'WITH PREMATURE VENTRICULAR OR ABERRANTLY CONDUCTED COMPLEXES':
    'con extrasístoles ventriculares o conducidas de forma aberrante',
  'RIGHT ATRIAL ENLARGEMENT': 'crecimiento auricular derecho',
  'INFERIOR INFARCT': 'infarto inferior',
  'INCOMPLETE LEFT BUNDLE BRANCH BLOCK': 'bloqueo incompleto de rama izquierda',
  'VOLTAGE CRITERIA FOR LEFT VENTRICULAR HYPERTROPHY':
    'criterios de voltaje para hipertrofia ventricular izquierda',
  'OR DIGITALIS EFFECT': 'o efecto digitálico',
  'BIFASCICULAR BLOCK': 'bloqueo bifascicular',
  'ST NO LONGER ELEVATED IN': 'el segmento ST ya no está elevado en',
  'WITH SLOW VENTRICULAR RESPONSE': 'con respuesta ventricular lenta',
  'ST ELEVATION NOW PRESENT IN': 'elevación del ST ahora presente en',
  'PREMATURE ECTOPIC COMPLEXES': 'extrasístoles ectópicas',
  'LEFT POSTERIOR FASCICULAR BLOCK': 'bloqueo fascicular posterior izquierdo',
  'T WAVE AMPLITUDE HAS DECREASED IN': 'la amplitud de la onda T ha disminuido en',
  'WITH A COMPETING JUNCTIONAL PACEMAKER': 'con un marcapasos de la unión competitivo',
  'RIGHT SUPERIOR AXIS DEVIATION': 'desviación del eje hacia la derecha y superior',
  'BIATRIAL ENLARGEMENT': 'crecimiento biauricular',
  'VENTRICULAR-PACED RHYTHM': 'ritmo de marcapasos ventricular',
  'ATRIAL-PACED RHYTHM': 'ritmo de marcapasos auricular',
  'T WAVE AMPLITUDE HAS INCREASED IN': 'la amplitud de la onda T ha aumentado en',
  'WITH QRS WIDENING': 'con ensanchamiento del QRS',
  'WITH 1ST DEGREE AV BLOCK': 'con bloqueo auriculoventricular de primer grado',
  'PROLONGED QT': 'QT prolongado',
  'WITH PROLONGED AV CONDUCTION': 'con conducción auriculoventricular prolongada',
  'RIGHT VENTRICULAR HYPERTROPHY': 'hipertrofia ventricular derecha',
  'WITH QRS WIDENING AND REPOLARIZATION ABNORMALITY':
    'con ensanchamiento del QRS y anomalía de la repolarización',
  'ATRIAL-SENSED VENTRICULAR-PACED RHYTHM':
    'ritmo de marcapasos con sensado auricular y estimulación ventricular',
  'AV SEQUENTIAL OR DUAL CHAMBER ELECTRONIC PACEMAKER':
    'marcapasos electrónico secuencial AV o bicameral',
  'PULMONARY DISEASE PATTERN': 'patrón de enfermedad pulmonar',
  'ACUTE MI / STEMI': 'infarto agudo de miocardio con elevación del ST (IAMCEST)',
  'INFERIOR-POSTERIOR INFARCT': 'infarto inferoposterior',
  'NONSPECIFIC INTRAVENTRICULAR CONDUCTION DELAY':
    'retraso inespecífico de la conducción intraventricular',
  'PREMATURE VENTRICULAR AND FUSION COMPLEXES': 'extrasístoles ventriculares y complejos de fusión',
  'IN A PATTERN OF BIGEMINY': 'en patrón de bigeminismo',
  'AV DUAL-PACED RHYTHM': 'ritmo de marcapasos bicameral (AV)',
  'SUPRAVENTRICULAR TACHYCARDIA': 'taquicardia supraventricular',
  'VENTRICULAR-PACED COMPLEXES': 'complejos de marcapasos ventricular',
  'WIDE QRS TACHYCARDIA': 'taquicardia con QRS ancho',
  "RSR' PATTERN IN V1": "patrón RSR' en V1",
  'ST LESS DEPRESSED IN': 'el segmento ST está menos descendido en',
  'VENTRICULAR TACHYCARDIA': 'taquicardia ventricular',
  'EARLY REPOLARIZATION': 'repolarización precoz',
  'ST MORE DEPRESSED IN': 'el segmento ST está más descendido en',
  'ANTEROLATERAL LEADS': 'derivaciones anterolaterales',
  'ELECTRONIC DEMAND PACING': 'marcapasos electrónico a demanda',
  'RBBB AND LEFT ANTERIOR FASCICULAR BLOCK':
    'bloqueo de rama derecha y bloqueo fascicular anterior izquierdo',
  'LATERAL INJURY PATTERN': 'patrón de lesión lateral',
  'BIVENTRICULAR PACEMAKER DETECTED': 'marcapasos biventricular detectado',
  'SUSPECT UNSPECIFIED PACEMAKER FAILURE': 'sospecha de falla del marcapasos no especificada',
  'WOLFF-PARKINSON-WHITE': 'síndrome de Wolff-Parkinson-White',
  'WITH VENTRICULAR ESCAPE COMPLEXES': 'con complejos de escape ventricular',
  'INFERIOR INJURY PATTERN': 'patrón de lesión inferior',
  'CONSIDER RIGHT VENTRICULAR INVOLVEMENT IN ACUTE INFERIOR INFARCT':
    'considerar compromiso del ventrículo derecho en el infarto inferior agudo',
  'ST ELEVATION HAS REPLACED ST DEPRESSION IN':
    'la elevación del ST ha reemplazado al descenso del ST en',
  'NONSPECIFIC INTRAVENTRICULAR BLOCK': 'bloqueo intraventricular inespecífico',
  'MASKED BY FASCICULAR BLOCK': 'enmascarado por bloqueo fascicular',
  'PEDIATRIC ECG ANALYSIS': 'análisis de ECG pediátrico',
  BLOCKED: 'bloqueada',
  'WITH UNDETERMINED RHYTHM IRREGULARITY': 'con irregularidad del ritmo indeterminada',
  'LEFTWARD AXIS': 'eje desviado hacia la izquierda',
  'WITH 2ND DEGREE SA BLOCK MOBITZ I': 'con bloqueo sinoauricular de segundo grado tipo Mobitz I',
  ACUTE: 'agudo',
  'ABNORMAL LEFT AXIS DEVIATION': 'desviación anormal del eje a la izquierda',
  'WITH COMPLETE HEART BLOCK': 'con bloqueo auriculoventricular completo',
  'NO P-WAVES FOUND': 'no se identifican ondas P',
  'ST LESS ELEVATED IN': 'el segmento ST está menos elevado en',
  'WITH RETROGRADE CONDUCTION': 'con conducción retrógrada',
  'ST MORE ELEVATED IN': 'el segmento ST está más elevado en',
  'JUNCTIONAL BRADYCARDIA': 'bradicardia de la unión',
  'WITH VARIABLE AV BLOCK': 'con bloqueo auriculoventricular variable',
  'ANTERIOR INJURY PATTERN': 'patrón de lesión anterior',
  'WITH JUNCTIONAL ESCAPE COMPLEXES': 'con complejos de escape de la unión',
  'ACUTE MI': 'infarto agudo de miocardio',
  'ACUTE PERICARDITIS': 'pericarditis aguda',
  'POSTERIOR INFARCT': 'infarto posterior',
  'IDIOVENTRICULAR RHYTHM': 'ritmo idioventricular',
  'WITH 2ND DEGREE SA BLOCK MOBITZ II': 'con bloqueo sinoauricular de segundo grado tipo Mobitz II',
  'R IN AVL': 'R en aVL',
  'SINUS/ATRIAL CAPTURE': 'captura sinusal/auricular',
  'AV DUAL-PACED COMPLEXES': 'complejos de marcapasos bicameral (AV)',
  'INFEROLATERAL INJURY PATTERN': 'patrón de lesión inferolateral',
  'RBBB AND LEFT POSTERIOR FASCICULAR BLOCK':
    'bloqueo de rama derecha y bloqueo fascicular posterior izquierdo',
  'ANTEROLATERAL INJURY PATTERN': 'patrón de lesión anterolateral',
  'ATRIAL-PACED COMPLEXES': 'complejos de marcapasos auricular',
  'WITH SINUS PAUSE': 'con pausa sinusal',
  'BIVENTRICULAR HYPERTROPHY': 'hipertrofia biventricular',
  'ABNORMAL RIGHT AXIS DEVIATION': 'desviación anormal del eje a la derecha',
  'SUPRAVENTRICULAR COMPLEXES': 'complejos supraventriculares',
  'WITH 2ND DEGREE AV BLOCK MOBITZ I':
    'con bloqueo auriculoventricular de segundo grado tipo Mobitz I',
  'WITH 2:1 AV CONDUCTION': 'con conducción auriculoventricular 2:1',
  'WITH AV DISSOCIATION': 'con disociación auriculoventricular',
  'MULTIFOCAL ATRIAL TACHYCARDIA': 'taquicardia auricular multifocal',
};

/** Enunciados de resumen que no se muestran junto a hallazgos concretos. */
export const HIDDEN_LABELS: ReadonlySet<string> = new Set([
  'ABNORMAL ECG',
  'NORMAL ECG',
  'otherwise normal ecg',
  'BORDERLINE ECG',
  'PEDIATRIC ECG ANALYSIS',
]);
